version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy
sphinx:
  builder: dirhtml
  fail_on_warning: true
  configuration: docs/conf.py
