# syntax=docker/dockerfile:1
FROM python:3.11-alpine
WORKDIR /tester
ENV DOCKER_TESTING = True
ENV FLIT_ROOT_INSTALL=1

COPY requirements requirements
COPY src/flask_imp src/flask_imp
COPY tests tests
COPY LICENSE LICENSE
COPY pyproject.toml pyproject.toml
COPY README.md README.md

RUN pip install -r requirements/tests.txt
RUN pip install -r requirements/build.txt
RUN flit install

ENTRYPOINT ["pytest"]
