# syntax=docker/dockerfile:1
FROM python:3.11-slim-buster
WORKDIR /tester
COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt
RUN pip install -r requirements.txt
RUN pip install -r requirements_dev.txt
COPY . .
RUN python3 setup.py install
RUN python3 -m pytest
ENTRYPOINT ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
