# syntax=docker/dockerfile:1
FROM python:3.9-slim-buster
WORKDIR /tester
COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt
RUN pip install -r requirements.txt
RUN pip install -r requirements_dev.txt
COPY . .
RUN python3 setup.py install
ENV DOCKER_TESTING = True
ENTRYPOINT ["pytest"]
