# syntax=docker/dockerfile:1
FROM python:3.8-alpine
WORKDIR /tester
ENV DOCKER_TESTING = True
ENV FLIT_ROOT_INSTALL=1
COPY tests tests
COPY flask_imp flask_imp
COPY pyproject.toml pyproject.toml
COPY requirements/development.txt requirements/development.txt
COPY requirements/main.txt requirements/main.txt
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
RUN pip install -r requirements/development.txt
RUN flit install
ENTRYPOINT ["pytest"]
