# syntax=docker/dockerfile:1
FROM python:3.12-slim-bookworm
WORKDIR /tester
ENV DOCKER_TESTING = True
ENV FLIT_ROOT_INSTALL=1
COPY tests tests
COPY flask_imp flask_imp
COPY pyproject.toml pyproject.toml
COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY LICENSE LICENSE
RUN pip install -r requirements_dev.txt
RUN flit install
ENTRYPOINT ["pytest"]
