# syntax=docker/dockerfile:1
FROM python:3.10-slim-buster
WORKDIR /tester
COPY test_app test_app
COPY tests tests
COPY src src
COPY pyproject.toml pyproject.toml
COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt
COPY setup.cfg setup.cfg
COPY setup.py setup.py
RUN pip install -r requirements_dev.txt
RUN python3 setup.py install
ENV DOCKER_TESTING = True
ENTRYPOINT ["pytest"]
